"""empty message

Revision ID: 2096997ace2d
Revises: 0e28e53c03b4
Create Date: 2020-01-18 22:34:16.413202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2096997ace2d'
down_revision = '0e28e53c03b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_table', sa.Column('num_persons', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_table', 'num_persons')
    # ### end Alembic commands ###
